// Chinese name mapping for NBA players.
// Priority order: player.name_zh (DB field) > player.chinese_name (DB field) > this map > original name.
// Add entries here as new players appear; the DB fields will take precedence once populated.
export const PLAYER_NAME_ZH_MAP: Record<string, string> = {
  // Superstars
  "LeBron James": "勒布朗·詹姆斯",
  "Nikola Jokić": "尼古拉·约基奇",
  "Stephen Curry": "斯蒂芬·库里",
  "Giannis Antetokounmpo": "扬尼斯·字母哥",
  "Luka Dončić": "卢卡·东契奇",
  "Shai Gilgeous-Alexander": "谢伊·吉尔杰斯-亚历山大",
  "Jayson Tatum": "杰森·塔图姆",
  "Joel Embiid": "乔尔·恩比德",
  "Kevin Durant": "凯文·杜兰特",
  "Anthony Davis": "安东尼·戴维斯",
  "Anthony Edwards": "安东尼·爱德华兹",
  "Victor Wembanyama": "文班亚马",
  "LaMelo Ball": "拉梅洛·鲍尔",
  "Paolo Banchero": "保罗·班凯罗",
  "Damian Lillard": "达米安·利拉德",
  "Devin Booker": "德文·布克",
  "Jalen Brunson": "杰伦·布伦森",
  "De'Aaron Fox": "德亚伦·福克斯",
  "Ja Morant": "贾·莫兰特",
  "Donovan Mitchell": "多诺万·米切尔",
  "Tyrese Haliburton": "泰里斯·哈利伯顿",
  // Stars
  "Cade Cunningham": "凯德·坎宁安",
  "Rui Hachimura": "八村塁",
  "Jaylin Williams": "杰林·威廉姆斯",
  "Isaiah Stewart": "以赛亚·斯图尔特",
  "Bam Adebayo": "巴姆·阿德巴约",
  "Jimmy Butler": "吉米·巴特勒",
  "Trae Young": "特雷·杨",
  "Darius Garland": "达里斯·加兰",
  "Evan Mobley": "埃文·莫布利",
  "Jarrett Allen": "贾雷特·艾伦",
  "Desmond Bane": "德斯蒙德·贝恩",
  "Jaren Jackson Jr.": "贾伦·杰克逊",
  "Brandon Ingram": "布兰登·英格拉姆",
  "Zion Williamson": "锡安·威廉森",
  "CJ McCollum": "CJ·麦科勒姆",
  "Karl-Anthony Towns": "卡尔-安东尼·唐斯",
  "Julius Randle": "朱利叶斯·兰德尔",
  "OG Anunoby": "OG·阿努诺比",
  "Scottie Barnes": "斯科蒂·巴恩斯",
  "Pascal Siakam": "帕斯卡尔·西亚卡姆",
  "Domantas Sabonis": "多曼塔斯·萨博尼斯",
  "Andrew Wiggins": "安德鲁·威金斯",
  "Klay Thompson": "克莱·汤普森",
  "Draymond Green": "德雷蒙德·格林",
  "Rudy Gobert": "鲁迪·戈贝尔",
  "Mike Conley": "迈克·康利",
  "Luguentz Dort": "卢根茨·多特",
  "Jalen Williams": "杰伦·威廉姆斯",
  "Josh Giddey": "乔什·吉迪",
  "Chet Holmgren": "切特·霍尔姆格伦",
  "Franz Wagner": "弗朗茨·瓦格纳",
  "Wendell Carter Jr.": "温德尔·卡特",
  "RJ Barrett": "RJ·巴雷特",
  "Immanuel Quickley": "伊曼纽尔·奎克利",
  "Miles Bridges": "迈尔斯·布里奇斯",
  "Terry Rozier": "特里·罗齐尔",
  "Jordan Poole": "乔丹·普尔",
  "Kyle Kuzma": "凯尔·库兹马",
  "Bradley Beal": "布莱德利·比尔",
  "Deandre Ayton": "德安德鲁·艾顿",
  "Mikal Bridges": "米卡尔·布里奇斯",
  "Cameron Johnson": "卡梅隆·约翰逊",
  "Royce O'Neale": "罗伊斯·奥尼尔",
  "Ben Simmons": "本·西蒙斯",
  "Tobias Harris": "托拜亚斯·哈里斯",
  "Tyrese Maxey": "泰里斯·马克西",
  "Paul George": "保罗·乔治",
  "Kawhi Leonard": "卡怀·伦纳德",
  "Russell Westbrook": "拉塞尔·威斯布鲁克",
  "Chris Paul": "克里斯·保罗",
  "James Harden": "詹姆斯·哈登",
  "Kyrie Irving": "凯里·欧文",
  "Nikola Vucevic": "尼古拉·武切维奇",
  "DeMar DeRozan": "德马尔·德罗赞",
  "Zach LaVine": "扎克·拉文",
  "Ayo Dosunmu": "阿约·多苏努",
  "Patrick Williams": "帕特里克·威廉姆斯",
  "Coby White": "科比·怀特",
  "Lauri Markkanen": "劳里·马尔卡宁",
  "Jordan Clarkson": "乔丹·克拉克森",
  "Collin Sexton": "科林·塞克斯顿",
  "Walker Kessler": "沃克·凯斯勒",
  "Keyonte George": "凯鸿特·乔治",
  "John Collins": "约翰·柯林斯",
  "Ochai Agbaji": "奥海·阿格巴吉",
  "Drew Eubanks": "德鲁·尤班克斯",
  "Scoot Henderson": "斯库特·亨德森",
  "Anfernee Simons": "安费尼·西蒙斯",
  "Jerami Grant": "杰拉米·格兰特",
  "Shaedon Sharpe": "沙登·夏普",
  "Kevin Porter Jr.": "凯文·波特",
  "Alperen Sengun": "阿尔佩伦·森贡",
  "Jabari Smith Jr.": "贾巴里·史密斯",
  "Fred VanVleet": "弗雷德·范弗利特",
  "Scottie Pippen Jr.": "斯科特·皮蓬",
  "Santi Aldama": "桑蒂·阿尔达马",
  "Luke Kennard": "卢克·肯纳德",
  "Jaden Ivey": "杰登·艾维",
  "Ausar Thompson": "奥萨·汤普森",
  "Marcus Sasser": "马库斯·萨瑟",
  "Bojan Bogdanovic": "博扬·博格达诺维奇",
  "Kelly Olynyk": "凯利·奥利尼克",
  "Talen Horton-Tucker": "塔伦·霍顿-塔克",
  "Keldon Johnson": "凯尔顿·约翰逊",
  "Tre Jones": "特雷·琼斯",
  "Devin Vassell": "德文·瓦塞尔",
  "Saddiq Bey": "萨迪克·贝伊",
  "Jordan Nwora": "约旦·努沃拉",
  "Moses Moody": "摩西·穆迪",
  "Jonathan Kuminga": "乔纳森·库明加",
  "Patrick Baldwin Jr.": "帕特里克·鲍德温",
  "Dario Saric": "达里奥·萨里奇",
  "Bol Bol": "博尔·博尔",
  "Markelle Fultz": "马克尔·富尔茨",
  "Cole Anthony": "科尔·安东尼",
  "Gary Harris": "加里·哈里斯",
  "Jonathan Isaac": "乔纳森·艾萨克",
  "Mo Bamba": "莫·班巴",
  "Naz Reid": "纳兹·里德",
  "Nickeil Alexander-Walker": "尼基尔·亚历山大-沃克",
  "Kyle Anderson": "凯尔·安德森",
  "Josh Hart": "乔什·哈特",
  "Mitchell Robinson": "米切尔·罗宾逊",
  "Donte DiVincenzo": "邓特·迪文森佐",
  "Isaiah Hartenstein": "以赛亚·哈滕斯坦",
  "Precious Achiuwa": "普雷舍斯·阿丘瓦",
  "Quentin Grimes": "昆汀·格莱姆斯",
  "Evan Fournier": "埃文·富尼耶",
  "Derrick Rose": "德里克·罗斯",
};

export function getPlayerDisplayName(
  player: { name: string; name_zh?: string | null; chinese_name?: string | null },
  lang: "zh" | "en",
): string {
  if (lang !== "zh") return player.name;
  return (
    player.name_zh ||
    player.chinese_name ||
    PLAYER_NAME_ZH_MAP[player.name] ||
    player.name
  );
}
