export type HeroPlayer = {
  id: string;
  name: string;
  nameZh: string;
  team: string;
  teamZh: string;
  number: string;
  position: string;
  portraitImage: string;
  jerseyImage: string;
  accent: string;
  accentLight: string;
};

const NBA_HEADSHOT = (id: number) =>
  `https://cdn.nba.com/headshots/nba/latest/1040x760/${id}.png`;

export const HERO_PLAYERS: HeroPlayer[] = [
  // === Superstars ===
  {
    id: "lebron",
    name: "LeBron James",
    nameZh: "勒布朗·詹姆斯",
    team: "LAL",
    teamZh: "湖人",
    number: "23",
    position: "SF",
    portraitImage: NBA_HEADSHOT(2544),
    jerseyImage: NBA_HEADSHOT(2544),
    accent: "#552583",
    accentLight: "#FDB927",
  },
  {
    id: "jokic",
    name: "Nikola Jokić",
    nameZh: "尼古拉·约基奇",
    team: "DEN",
    teamZh: "掘金",
    number: "15",
    position: "C",
    portraitImage: NBA_HEADSHOT(203999),
    jerseyImage: NBA_HEADSHOT(203999),
    accent: "#0E2240",
    accentLight: "#FEC524",
  },
  {
    id: "curry",
    name: "Stephen Curry",
    nameZh: "斯蒂芬·库里",
    team: "GSW",
    teamZh: "勇士",
    number: "30",
    position: "PG",
    portraitImage: NBA_HEADSHOT(201939),
    jerseyImage: NBA_HEADSHOT(201939),
    accent: "#1D428A",
    accentLight: "#FFC72C",
  },
  {
    id: "giannis",
    name: "Giannis Antetokounmpo",
    nameZh: "扬尼斯·字母哥",
    team: "MIL",
    teamZh: "雄鹿",
    number: "34",
    position: "PF",
    portraitImage: NBA_HEADSHOT(203507),
    jerseyImage: NBA_HEADSHOT(203507),
    accent: "#00471B",
    accentLight: "#EEE1C6",
  },
  {
    id: "luka",
    name: "Luka Dončić",
    nameZh: "卢卡·东契奇",
    team: "DAL",
    teamZh: "独行侠",
    number: "77",
    position: "PG",
    portraitImage: NBA_HEADSHOT(1629029),
    jerseyImage: NBA_HEADSHOT(1629029),
    accent: "#00538C",
    accentLight: "#B8C4CA",
  },
  {
    id: "shai",
    name: "Shai Gilgeous-Alexander",
    nameZh: "亚历山大",
    team: "OKC",
    teamZh: "雷霆",
    number: "2",
    position: "SG",
    portraitImage: NBA_HEADSHOT(1628983),
    jerseyImage: NBA_HEADSHOT(1628983),
    accent: "#007AC1",
    accentLight: "#EF6100",
  },
  {
    id: "tatum",
    name: "Jayson Tatum",
    nameZh: "杰森·塔图姆",
    team: "BOS",
    teamZh: "凯尔特人",
    number: "0",
    position: "SF",
    portraitImage: NBA_HEADSHOT(1628369),
    jerseyImage: NBA_HEADSHOT(1628369),
    accent: "#007A33",
    accentLight: "#BA9653",
  },
  {
    id: "embiid",
    name: "Joel Embiid",
    nameZh: "乔尔·恩比德",
    team: "PHI",
    teamZh: "76人",
    number: "21",
    position: "C",
    portraitImage: NBA_HEADSHOT(203954),
    jerseyImage: NBA_HEADSHOT(203954),
    accent: "#006BB6",
    accentLight: "#ED174C",
  },
  {
    id: "durant",
    name: "Kevin Durant",
    nameZh: "凯文·杜兰特",
    team: "PHX",
    teamZh: "太阳",
    number: "35",
    position: "PF",
    portraitImage: NBA_HEADSHOT(201142),
    jerseyImage: NBA_HEADSHOT(201142),
    accent: "#1D1160",
    accentLight: "#E56020",
  },
  {
    id: "ad",
    name: "Anthony Davis",
    nameZh: "安东尼·戴维斯",
    team: "LAL",
    teamZh: "湖人",
    number: "3",
    position: "PF",
    portraitImage: NBA_HEADSHOT(203076),
    jerseyImage: NBA_HEADSHOT(203076),
    accent: "#552583",
    accentLight: "#FDB927",
  },
  // === Young Stars ===
  {
    id: "ant",
    name: "Anthony Edwards",
    nameZh: "安东尼·爱德华兹",
    team: "MIN",
    teamZh: "森林狼",
    number: "5",
    position: "SG",
    portraitImage: NBA_HEADSHOT(1630162),
    jerseyImage: NBA_HEADSHOT(1630162),
    accent: "#0C2340",
    accentLight: "#236192",
  },
  {
    id: "wemby",
    name: "Victor Wembanyama",
    nameZh: "文班亚马",
    team: "SAS",
    teamZh: "马刺",
    number: "1",
    position: "C",
    portraitImage: NBA_HEADSHOT(1641705),
    jerseyImage: NBA_HEADSHOT(1641705),
    accent: "#C4CED4",
    accentLight: "#000000",
  },
  {
    id: "lamelo",
    name: "LaMelo Ball",
    nameZh: "拉梅洛·鲍尔",
    team: "CHA",
    teamZh: "黄蜂",
    number: "1",
    position: "PG",
    portraitImage: NBA_HEADSHOT(1630163),
    jerseyImage: NBA_HEADSHOT(1630163),
    accent: "#1D1160",
    accentLight: "#00788C",
  },
  {
    id: "chet",
    name: "Chet Holmgren",
    nameZh: "切特·霍姆格伦",
    team: "OKC",
    teamZh: "雷霆",
    number: "7",
    position: "PF",
    portraitImage: NBA_HEADSHOT(1631096),
    jerseyImage: NBA_HEADSHOT(1631096),
    accent: "#007AC1",
    accentLight: "#EF6100",
  },
  {
    id: "paolo",
    name: "Paolo Banchero",
    nameZh: "保罗·班凯罗",
    team: "ORL",
    teamZh: "魔术",
    number: "5",
    position: "PF",
    portraitImage: NBA_HEADSHOT(1631094),
    jerseyImage: NBA_HEADSHOT(1631094),
    accent: "#0077C0",
    accentLight: "#C4CED4",
  },
  // === All-Stars ===
  {
    id: "dame",
    name: "Damian Lillard",
    nameZh: "达米安·利拉德",
    team: "MIL",
    teamZh: "雄鹿",
    number: "0",
    position: "PG",
    portraitImage: NBA_HEADSHOT(203081),
    jerseyImage: NBA_HEADSHOT(203081),
    accent: "#00471B",
    accentLight: "#EEE1C6",
  },
  {
    id: "booker",
    name: "Devin Booker",
    nameZh: "德文·布克",
    team: "PHX",
    teamZh: "太阳",
    number: "1",
    position: "SG",
    portraitImage: NBA_HEADSHOT(1626164),
    jerseyImage: NBA_HEADSHOT(1626164),
    accent: "#1D1160",
    accentLight: "#E56020",
  },
  {
    id: "jimmy",
    name: "Jimmy Butler",
    nameZh: "吉米·巴特勒",
    team: "MIA",
    teamZh: "热火",
    number: "22",
    position: "SF",
    portraitImage: NBA_HEADSHOT(202710),
    jerseyImage: NBA_HEADSHOT(202710),
    accent: "#98002E",
    accentLight: "#F9A01B",
  },
  {
    id: "kawhi",
    name: "Kawhi Leonard",
    nameZh: "科怀·伦纳德",
    team: "LAC",
    teamZh: "快船",
    number: "2",
    position: "SF",
    portraitImage: NBA_HEADSHOT(202695),
    jerseyImage: NBA_HEADSHOT(202695),
    accent: "#C8102E",
    accentLight: "#1D428A",
  },
  {
    id: "harden",
    name: "James Harden",
    nameZh: "詹姆斯·哈登",
    team: "LAC",
    teamZh: "快船",
    number: "1",
    position: "PG",
    portraitImage: NBA_HEADSHOT(201935),
    jerseyImage: NBA_HEADSHOT(201935),
    accent: "#C8102E",
    accentLight: "#1D428A",
  },
  {
    id: "brunson",
    name: "Jalen Brunson",
    nameZh: "杰伦·布伦森",
    team: "NYK",
    teamZh: "尼克斯",
    number: "11",
    position: "PG",
    portraitImage: NBA_HEADSHOT(1628973),
    jerseyImage: NBA_HEADSHOT(1628973),
    accent: "#006BB6",
    accentLight: "#F58426",
  },
  {
    id: "fox",
    name: "De'Aaron Fox",
    nameZh: "福克斯",
    team: "SAC",
    teamZh: "国王",
    number: "5",
    position: "PG",
    portraitImage: NBA_HEADSHOT(1628368),
    jerseyImage: NBA_HEADSHOT(1628368),
    accent: "#5A2D81",
    accentLight: "#63727A",
  },
  {
    id: "morant",
    name: "Ja Morant",
    nameZh: "贾·莫兰特",
    team: "MEM",
    teamZh: "灰熊",
    number: "12",
    position: "PG",
    portraitImage: NBA_HEADSHOT(1629630),
    jerseyImage: NBA_HEADSHOT(1629630),
    accent: "#5D76A9",
    accentLight: "#12173F",
  },
  {
    id: "mitchell",
    name: "Donovan Mitchell",
    nameZh: "多诺万·米切尔",
    team: "CLE",
    teamZh: "骑士",
    number: "45",
    position: "SG",
    portraitImage: NBA_HEADSHOT(1628378),
    jerseyImage: NBA_HEADSHOT(1628378),
    accent: "#860038",
    accentLight: "#FDBB30",
  },
  {
    id: "tyrese",
    name: "Tyrese Haliburton",
    nameZh: "泰里斯·哈利伯顿",
    team: "IND",
    teamZh: "步行者",
    number: "0",
    position: "PG",
    portraitImage: NBA_HEADSHOT(1630169),
    jerseyImage: NBA_HEADSHOT(1630169),
    accent: "#002D62",
    accentLight: "#FDBB30",
  },
];
