// Multi-position eligibility map for NBA players (ESPN/Yahoo style)
// Format: "Player Name" → "POS1/POS2" (slash-separated, primary position first)
// Players not in this map keep their default single position.

export const PLAYER_POSITIONS: Record<string, string> = {
  // === TOP STARS ===
  "Stephen Curry": "PG/SG",
  "Nikola Jokic": "C",
  "Luka Doncic": "PG/SG",
  "Shai Gilgeous-Alexander": "PG/SG",
  "Giannis Antetokounmpo": "PF/C",
  "Victor Wembanyama": "C/PF",
  "Anthony Davis": "PF/C",
  "Jayson Tatum": "SF/PF",
  "Tyrese Haliburton": "PG",
  "Anthony Edwards": "SG/SF",
  "Kevin Durant": "SF/PF",
  "Donovan Mitchell": "SG",
  "Chet Holmgren": "C/PF",
  "Jaylen Brown": "SG/SF",
  "Domantas Sabonis": "C/PF",
  "Trae Young": "PG",
  "LaMelo Ball": "PG/SG",
  "De'Aaron Fox": "PG",
  "Kyrie Irving": "PG/SG",
  "Devin Booker": "SG/PG",
  "Ja Morant": "PG",
  "Bam Adebayo": "C/PF",
  "Pascal Siakam": "PF/SF",
  "Scottie Barnes": "SF/PF",
  "Karl-Anthony Towns": "C/PF",
  "Jalen Brunson": "PG",
  "Paul George": "SF/PF",
  "Lauri Markkanen": "PF/SF",
  "Jaren Jackson Jr.": "PF/C",
  "Franz Wagner": "SF/PF",
  "LeBron James": "SF/PF",

  // === 31-60 ===
  "Evan Mobley": "PF/C",
  "Desmond Bane": "SG/SF",
  "Jalen Williams": "SG/SF",
  "Mikal Bridges": "SF/SG",
  "Jimmy Butler": "SF/PF",
  "Zion Williamson": "PF",
  "Brandon Ingram": "SF/SG",
  "Darius Garland": "PG",
  "Alperen Sengun": "C",
  "Fred VanVleet": "PG/SG",
  "Anfernee Simons": "SG/PG",
  "Dejounte Murray": "PG/SG",
  "Jrue Holiday": "PG/SG",
  "OG Anunoby": "SF/PF",
  "Tyler Herro": "SG/PG",
  "Derrick White": "SG/PG",
  "Myles Turner": "C",
  "Jakob Poeltl": "C",
  "Coby White": "SG/PG",
  "Immanuel Quickley": "PG/SG",
  "Nikola Vucevic": "C",
  "Cade Cunningham": "PG/SG",
  "Aaron Gordon": "PF/SF",
  "Herbert Jones": "SF/PF",
  "Cameron Johnson": "SF/PF",
  "Brook Lopez": "C",
  "Austin Reaves": "SG/PG",
  "Bradley Beal": "SG/SF",
  "Miles Bridges": "PF/SF",
  "Khris Middleton": "SF/SG",

  // === 61-100 ===
  "Jamal Murray": "PG/SG",
  "Jarrett Allen": "C",
  "Josh Hart": "SG/SF",
  "Jusuf Nurkic": "C",
  "Jonathan Kuminga": "PF/SF",
  "Michael Porter Jr.": "SF/PF",
  "Jordan Poole": "SG/PG",
  "Tobias Harris": "PF/SF",
  "Marcus Smart": "PG/SG",
  "Terry Rozier": "PG/SG",
  "Chris Paul": "PG",
  "Jonas Valanciunas": "C",
  "Cam Thomas": "SG",
  "Nic Claxton": "C",
  "Mark Williams": "C",
  "Keldon Johnson": "SF/SG",
  "Kyle Kuzma": "PF/SF",
  "Trey Murphy III": "SF/SG",
  "Jaden McDaniels": "SF/PF",
  "Bogdan Bogdanovic": "SG/SF",
  "Deandre Ayton": "C",
  "Dennis Schroder": "PG",
  "Jalen Green": "SG",
  "Jabari Smith Jr.": "PF/C",
  "RJ Barrett": "SG/SF",
  "Malik Monk": "SG/PG",
  "Daniel Gafford": "C",
  "Spencer Dinwiddie": "PG/SG",
  "Bruce Brown": "SG/SF",
  "Naz Reid": "C/PF",
  "Walker Kessler": "C",
  "Dillon Brooks": "SF/SG",
  "Andrew Wiggins": "SF/PF",
  "John Collins": "PF/C",
  "CJ McCollum": "SG/PG",
  "Collin Sexton": "SG/PG",
  "Draymond Green": "PF/C",
  "Keegan Murray": "SF/PF",
  "Patrick Williams": "PF/SF",
  "Ivica Zubac": "C",

  // === 101-150 ===
  "Josh Giddey": "PG/SG",
  "Russell Westbrook": "PG",
  "Wendell Carter Jr.": "C/PF",
  "Jaden Ivey": "SG/PG",
  "Tyus Jones": "PG",
  "Grayson Allen": "SG/SF",
  "De'Andre Hunter": "SF/PF",
  "Onyeka Okongwu": "C/PF",
  "Bobby Portis": "PF/C",
  "Gary Trent Jr.": "SG",
  "Alex Caruso": "SG/PG",
  "Isaiah Hartenstein": "C",
  "Brandin Podziemski": "SG/PG",
  "Amen Thompson": "SG/SF",
  "Ausar Thompson": "SF/SG",
  "Ayo Dosunmu": "PG/SG",
  "Jeremy Sochan": "PF/SF",
  "Zach LaVine": "SG/SF",
  "Dereck Lively II": "C",
  "Brandon Miller": "SF/SG",
  "Grant Williams": "PF/SF",
  "Aaron Nesmith": "SF/SG",
  "Keyonte George": "PG/SG",
  "Devin Vassell": "SG/SF",
  "Obi Toppin": "PF",
  "Nick Richards": "C",
  "Norman Powell": "SG/SF",
  "Buddy Hield": "SG",
  "Tim Hardaway Jr.": "SG",
  "Isaiah Jackson": "C/PF",
  "Kelly Oubre Jr.": "SF/SG",
  "Jalen Suggs": "PG/SG",
  "Paolo Banchero": "PF/SF",
  "Al Horford": "C/PF",
  "Dalton Knecht": "SG/SF",
  "Jerami Grant": "SF/PF",
  "PJ Washington": "PF/SF",
  "Scoot Henderson": "PG",
  "Mitchell Robinson": "C",
  "Shaedon Sharpe": "SG",
  "Clint Capela": "C",
  "Caleb Martin": "SF/PF",

  // === 151-200 ===
  "Jaime Jaquez Jr.": "SF/SG",
  "Gradey Dick": "SG",
  "Jonathan Isaac": "PF/SF",
  "Caris LeVert": "SG/SF",
  "Bilal Coulibaly": "SF/SG",
  "Jalen Duren": "C",
  "Malik Beasley": "SG",
  "Luguentz Dort": "SG/SF",
  "Rudy Gobert": "C",
  "Isaiah Stewart": "C/PF",
  "Jalen Johnson": "PF/SF",
  "Jordan Clarkson": "SG/PG",
  "Terance Mann": "SG/SF",
  "Santi Aldama": "PF/C",
  "Bennedict Mathurin": "SG/SF",
  "GG Jackson": "PF/SF",
  "Precious Achiuwa": "PF/C",
  "Kyle Anderson": "SF/PF",
  "Tari Eason": "SF/PF",
  "Donte DiVincenzo": "SG/PG",
  "Cole Anthony": "PG/SG",
  "Robert Williams III": "C",
  "Andrew Nembhard": "PG/SG",

  // === 201+ Notable ===
  "Klay Thompson": "SG/SF",
  "James Harden": "PG/SG",
  "Kawhi Leonard": "SF/PF",
  "D'Angelo Russell": "PG/SG",
  "Rui Hachimura": "PF/SF",
  "Tyrese Maxey": "PG/SG",
  "Joel Embiid": "C",
  "Harrison Barnes": "SF/PF",
  "Payton Pritchard": "PG/SG",
  "Sam Hauser": "SF",
  "Dorian Finney-Smith": "SF/PF",
  "Corey Kispert": "SF/SG",
  "Kyle Filipowski": "PF/C",
  "Ryan Rollins": "SG/PG",
  "Stephon Castle": "PG/SG",
  "Zaccharie Risacher": "SF/PF",
  "Alex Sarr": "C/PF",
  "Donovan Clingan": "C",
  "Matas Buzelis": "SF/PF",
  "Rob Dillingham": "PG",
  "Dalton Connect": "SG",
  "Cody Williams": "SF/SG",
  "Tidjane Salaun": "SF/PF",
  "Jared McCain": "SG/PG",
  "Ja'Kobe Walter": "SG",
  "Devin Carter": "SG/PG",
  "Carlton Carrington": "PG/SG",
  "Tristan da Silva": "SF/PF",
  "Yves Missi": "C",
  "Nikola Topic": "PG",
  "Dillon Jones": "SF/SG",
  "Jaylen Wells": "SG/SF",
  "Oso Ighodaro": "PF/C",
  "Pelle Larsson": "SG",
  "Ty Jerome": "PG",
  "Trey Jemison": "C",
  "Jarace Walker": "PF/SF",
  "Taylor Hendricks": "PF/SF",
  "Keyontae Johnson": "SF/PF",
  "Tre Mann": "PG/SG",
  "Kelly Olynyk": "C/PF",
  "Chris Boucher": "PF/C",
  "Jabari Walker": "PF",
  "Cam Whitmore": "SF/SG",
  "Josh Christopher": "SG",
  "Cam Reddish": "SF/SG",
  "Jarred Vanderbilt": "PF/SF",
  "Jaxson Hayes": "C",
  "Christian Wood": "C/PF",
  "Georges Niang": "PF/SF",
  "Dean Wade": "PF/SF",
  "Taurean Prince": "SF/PF",
  "Moritz Wagner": "C/PF",
  "Goga Bitadze": "C",
  "KJ Martin": "PF/SF",
  "Guerschon Yabusele": "PF/C",
  "Bol Bol": "C/PF",
  "Andre Drummond": "C",
  "Naji Marshall": "SF/PF",
  "Ziaire Williams": "SF/SG",
  "Jake LaRavia": "SF/PF",
  "Davion Mitchell": "PG/SG",
  "Max Strus": "SG/SF",
  "Kenrich Williams": "SF/PF",
  "Gordon Hayward": "SF",
  "Jeff Green": "PF/SF",
  "Xavier Tillman": "PF/C",
  "David Roddy": "SF/PF",
  "Lindy Waters III": "SF",
  "Doug McDermott": "SF",
  "Julian Champagnie": "SF",
  "Luke Kennard": "SG",
  "Vince Williams Jr.": "SG/SF",
  "Aaron Wiggins": "SG/SF",
  "Cason Wallace": "PG/SG",
  "Jaylin Williams": "PF/C",
  "Royce O'Neale": "SF/PF",
  "Jose Alvarado": "PG",
  "Patrick Beverley": "PG",
  "Monte Morris": "PG",
  "Eric Gordon": "SG",
  "Kyle Lowry": "PG",
  "Markelle Fultz": "PG",
  "Anthony Black": "PG/SG",
  "Josh Okogie": "SG/SF",
  "Gary Harris": "SG",
  "Johnny Davis": "SG/PG",
  "Bones Hyland": "PG/SG",
  "Kris Dunn": "PG/SG",
  "Amir Coffey": "SG/SF",
  "Landry Shamet": "SG",
  "Pat Connaughton": "SG/SF",
  "Josh Richardson": "SG/SF",
  "Haywood Highsmith": "SF/PF",
  "Caleb Houstan": "SF",
  "Isaiah Joe": "SG",
  "Maxi Kleber": "PF/C",
  "Trey Lyles": "PF/C",
  "Dwight Powell": "C/PF",
  "Marvin Bagley III": "PF/C",
  "AJ Griffin": "SF/SG",
  "Jaylen Nowell": "SG",
  "Danilo Gallinari": "PF/SF",
  "Ochai Agbaji": "SG/SF",
  "Kevin Huerter": "SG/SF",
};
